- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install packages
  ansible.builtin.apt:
    name:
      - git
      - stow
      - vim
      - tmux
      - curl
      - wget
      - xclip
      - fzf
      - build-essential
      - unzip
      - podman
    state: present
  become: true
