- name: Remove default conflicting dotfiles
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/{{ item }}"
    state: absent
  loop:
    - .bashrc
    - .vimrc
    - .tmux.conf
    - .gitconfig

- name: Stow dotfiles
  ansible.builtin.command:
    cmd: stow .
    chdir: "{{ ansible_facts['env']['HOME'] }}/dotfiles"
  changed_when: true
