- name: Setup development environment
  hosts: localhost
  connection: local
  roles:
    - role: packages
      tags: packages
    - role: dotfiles
      tags: dotfiles
    - role: tools
      tags: tools
